language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-24
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - $ANDROID_TARGET
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

licenses:
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  - 'android-sdk-preview-license-.+'

stages:
  - name: lint
    if: NOT branch = master
  - name: tests
    if: NOT branch = master
  - name: instrumental-tests
    if: branch = master OR tag

jobs:
  include:
    - stage: lint
      script:
        - ./gradlew detektLint;
        - ./gradlew lintDebug
    - stage: tests
      script:
        - ./gradlew testDebugUnitTest jacocoTestReport
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: instrumental-tests
      script:
        - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
        - emulator -avd test -no-window &
        - android-wait-for-emulator
        - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
        - ./gradlew connectedAndroidTest

before_deploy:
  - git config --local user.name "PexegoUva"
  - git config --local user.email "samuelvv22@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(./gradlew -q printVersionName)}
  - echo $TRAVIS_TAG
  - git tag $TRAVIS_TAG
deploy:
  - provider: releases
    api_key: "$GITHUB_API_KEY"
    file: app/build/outputs/apk/debug/*
    file_glob: true
    skip_cleanup: true
    prerelease: true
    on:
      branch: master
